### ISSUE TITLE
Using SQL Server as DataSource Type

### ISSUE THREAD

**Issue by trix4rabbit** [thabart/SimpleIdentityServer#119]
In the project [03.Host Layer].[SimpleIdentityServer.Startup].Startup.cs, under public void ConfigureServices, when DataSource is changed to be DataSourceTypes.sql (rather than DataSourceType), the server no longer starts. 

Things I have done (Windows 7 x64 with RC 1.0.1 and 1.0.2)
1. Changed the connection string but the database SimpleIdentityServer does not get created nor could I find a db file for me to restore within the projects. 
2. The code looks to find translation support, but will error out because the value returned is null.

**Comment by thabart** [comment]
1. Open a command prompt
2. Navigate to the project "SimpleIdentityServer.DataAccess.SqlServer"
3. In "appsettings.json" Update the connection string 
4. Execute the command "dnx ef database update", the table will be created via entity framework migration.

**Comment by thabart** [comment]
Is-it working ?

**Comment by trix4rabbit** [comment]
This is working now.  Passing in the argument "database update" was the step I was missing.  I tested this from command line and within visual studios by changing the launchSettings.json file.    By setting the HostingOptions.IsDataMigrated = to true, a default client (as well as other OpenId values) were inserted into the database.  

Thanks
