### ISSUE TITLE
Modify IdP

### ISSUE THREAD

**Issue by Pierpaolo1992** [thabart/SimpleIdentityServer#245]
Hi, is there a way to modify this IdP for integrating itself for WebRTC?

**Comment by thabart** [comment]
Hi,

I checked the documentation about the security of WebRTC. But the proposal is still a draft version ...(https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-12#section-5.6). You can implement your own idp proxy and add the following endpoints (as suggested here : https://github.com/mozilla/fxa-webrtc-idp)
=> "id-proxy"
=> "sign" 
=> "verify"
=> etc ...

The operation will call the idp provider endpoints to check the identity token assertion. Behind the scene the instrospection edp is used by the **idp proxy** to check the access_token or identity_token. You can refer to this repository (https://github.com/mozilla/fxa-webrtc-idp) for more information.

At the moment I'm working on the logging system with ODATA, if have free time I will implement a proxy and add it to my "well-known" edp.
